# Generated by Django 2.2.6 on 2019-11-05 02:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('provider', models.TextField(null=True)),
                ('provider_resource_path', models.TextField(null=True)),
                ('file_format', models.TextField()),
                ('stage', models.TextField()),
                ('status', models.TextField(default='INITIALIZED')),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EquityData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exchange', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.Data')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.Symbol')),
            ],
        ),
    ]
