# Generated by Django 2.2.6 on 2019-11-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='location',
            new_name='file_location',
        ),
        migrations.AddField(
            model_name='data',
            name='search_args',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='search_kwargs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='stage',
            field=models.TextField(default='ORIGINAL'),
        ),
        migrations.AlterField(
            model_name='equitydata',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.Data'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
